# exceptions

class UserError(Exception):
    pass
