{
    "config": {
        "abort": {
            "single_instance_allowed": "M\u00e1r konfigur\u00e1lva van. Csak egy konfigur\u00e1ci\u00f3 lehets\u00e9ges."
        },
        "error": {
            "cannot_connect": "Sikertelen csatlakoz\u00e1s",
            "unknown": "V\u00e1ratlan hiba"
        },
        "step": {
            "user": {
                "data": {
                    "host": "Hoszt",
                    "password": "Jelsz\u00f3",
                    "username": "Felhaszn\u00e1l\u00f3n\u00e9v"
                },
                "data_description": {
                    "host": "A Lutron f\u0151 \u00e1tj\u00e1tsz\u00f3 g\u00e9pneve vagy IP-c\u00edme."
                },
                "description": "K\u00e9rj\u00fck, adja meg a f\u0151 \u00e1tj\u00e1tsz\u00f3 bejelentkez\u00e9si adatait",
                "title": "F\u0151 \u00e1tj\u00e1tsz\u00f3 be\u00e1ll\u00edt\u00e1sa"
            }
        }
    },
    "issues": {
        "deprecated_yaml_import_issue_cannot_connect": {
            "description": "A Lutron konfigur\u00e1l\u00e1sa YAML haszn\u00e1lat\u00e1val megsz\u0171nik, de hiba t\u00f6rt\u00e9nt a YAML konfigur\u00e1ci\u00f3 import\u00e1l\u00e1sa sor\u00e1n.\n\nAmiket megpr\u00f3b\u00e1lhat:\n- Ellen\u0151rizze, hogy a Home Assistant el\u00e9ri-e a f\u0151 \u00e1tj\u00e1tsz\u00f3t.\n- Ind\u00edtsa \u00fajra a f\u0151 \u00e1tj\u00e1tsz\u00f3t azzal, hogy kih\u00fazza 60 m\u00e1sodpercre.\n- Pr\u00f3b\u00e1ljon bejelentkezni a f\u0151 \u00e1tj\u00e1tsz\u00f3ba a megadott IP c\u00edmen egy webb\u00f6ng\u00e9sz\u0151ben, ugyanazzal a bejelentkez\u00e9si adatokkal.\n\nEzut\u00e1n ind\u00edtsa \u00fajra a Home Assistantot, hogy \u00fajra megpr\u00f3b\u00e1lja import\u00e1lni az integr\u00e1ci\u00f3t.\n\nAlternat\u00edv megold\u00e1sk\u00e9nt elt\u00e1vol\u00edthatja a Lutron konfigur\u00e1ci\u00f3j\u00e1t a YAML konfigur\u00e1ci\u00f3j\u00e1b\u00f3l, \u00fajraind\u00edthatja a Home Assistantot \u00e9s manu\u00e1lisan adhatja hozz\u00e1 a Lutron integr\u00e1ci\u00f3t.",
            "title": "A Lutron YAML konfigur\u00e1ci\u00f3 import\u00e1l\u00e1s nem siker\u00fclt - szerver csatlakoz\u00e1si hiba"
        },
        "deprecated_yaml_import_issue_unknown": {
            "description": "A Lutron konfigur\u00e1l\u00e1sa YAML haszn\u00e1lat\u00e1val megsz\u0171nik, de ismeretlen hiba t\u00f6rt\u00e9nt a megl\u00e9v\u0151 konfigur\u00e1ci\u00f3 import\u00e1l\u00e1sa sor\u00e1n.\nA be\u00e1ll\u00edt\u00e1s nem folytat\u00f3dik.\n\nA specifikus hiba a napl\u00f3kban tal\u00e1lhat\u00f3. A legval\u00f3sz\u00edn\u0171bb ok egy h\u00e1l\u00f3zati hiba, a f\u0151 \u00e1tj\u00e1tsz\u00f3 nem m\u0171k\u00f6dik vagy \u00e9rv\u00e9nytelen konfigur\u00e1ci\u00f3val rendelkezik.\n\nEllen\u0151rizze, hogy a Lutron rendszere megfelel\u0151en m\u0171k\u00f6dik-e \u00e9s ind\u00edtsa \u00fajra a Home Assistantot, hogy \u00fajra megpr\u00f3b\u00e1lja az import\u00e1l\u00e1st.\n\nAlternat\u00edv megold\u00e1sk\u00e9nt elt\u00e1vol\u00edthatja a Lutron konfigur\u00e1ci\u00f3j\u00e1t a YAML konfigur\u00e1ci\u00f3j\u00e1b\u00f3l, \u00fajraind\u00edthatja a Home Assistantot \u00e9s manu\u00e1lisan adhatja hozz\u00e1 a Lutron integr\u00e1ci\u00f3t.",
            "title": "A Lutron YAML konfigur\u00e1ci\u00f3 import\u00e1l\u00e1si k\u00e9relme ismeretlen hiba miatt meghi\u00fasult"
        }
    }
}