Traceback (most recent call last):
  File "/home/snd/src/slidingpuzzle/test.py", line 4, in <module>
    s1 = search(b, heuristic=linear_conflict_distance)
  File "/home/snd/src/slidingpuzzle/src/slidingpuzzle/algorithms.py", line 579, in search
    raise ValueError(f"The provided board is not solvable:\n{board}")
ValueError: The provided board is not solvable:
[[2 1 3]
 [4 5 6]
 [7 8 0]]
